src/game1/Models/FaceInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace game1.Models
{
    public class FaceInfo
    {
        public int FaceCount { get; set; }
        public string Name { get; set; }
    }
}

src/game1/Controllers/HelloWorldController.cs
using game1.Models;
using Microsoft.ApplicationInsights;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace game1.Controllers
{
    public class HelloWorldController : Controller
    {
        TelemetryClient tc = new TelemetryClient();
        // 
        // GET: /HelloWorld/

        [HttpPost]
        public ActionResult Index(string userName, int count)
        {
            FaceInfo fi = new FaceInfo();
            fi.Name = userName;
            fi.FaceCount = count;
            return RedirectToAction("Welcome",fi);
        }
        [HttpGet]
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult About()
        {

            return View();
        }
        // 
        // GET: /HelloWorld/Welcome/ 

        //public string Welcome(string name, int ID = 1)
        //{
        //    tc.TrackEvent("welcome");
        //    return HtmlEncoder.Default.Encode($"Hello {name}, ID: {ID}");
        //}
        public ActionResult Welcome(FaceInfo fi)
        {
            tc.TrackEvent("Generating....");
            ViewData["Message"] = "Hello " + fi.Name;
            ViewData["FaceCount"] = fi.FaceCount;
            List<String> faces = DrawingHelper.Draw(fi.FaceCount).Select(t => t.ToString()).ToList();
            return View(faces);
        }
    }
}

src/game1/Views/HelloWorld/About.cshtml
@{
    ViewData["Title"] = "About";
}

<h2>About</h2>

<p>Hello from our About Template!</p>

src/game1/Views/HelloWorld/Index.cshtml
@model game1.Models.FaceInfo
@{
    ViewData["Title"] = "Index";
}

<h2>--------------HELLO--------------</h2>
<hr />
@using (Html.BeginForm())
{
    <input type="text" name="userName" />
    <input type="text" name="count" />
    <input type="submit" />
}>

<p>Hello to many little faces!</p>

src/game1/Views/HelloWorld/Welcome.cshtml
@{
    ViewData["Title"] = "Welcome";
}
@model List<String>
<h2>Welcome to Winnie's app</h2>

<p>This is my first web app.</p>

@foreach(var element in Model)
{
    <li>@ViewData["Message"]</li>
    <pre>@Html.DisplayFor(m=>element)</pre>
}

src/game1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GAME</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
   
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="HelloWorld" asp-action="Welcome" class="navbar-brand">Little Face</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li><a asp-area="" asp-controller="HelloWorld" asp-action="Index">Index</a></li>*@
                    <li><a asp-area="" asp-controller="HelloWorld" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="HelloWorld" asp-action="Welcome">Welcome</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - game1</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/game1/Views/Shared/_MyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
   
</head>
<body>
    <div style="color: white; background-image: url(/imgs/puppy.jpg); height: 200px;width: 400px;border:1px solid black;">
        <h2><strong>Little Face Random </strong></h2>
    </div>
    <div>
        @RenderBody()
    </div>
</body>
</html>